inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'db/**/*'
    - 'Gemfile'
    - 'spec/spec_helper.rb'
    - 'spec/factories/*'
    - 'vendor/**/*'
